version: "3.9"

networks:
  infra_internal:
    external: true

services:
  backend:
    build: ./Backend
    container_name: 4i-backend
    restart: unless-stopped
    env_file:
      - ./Backend/.env
    networks:
      - infra_internal
    ports:
      - "127.0.0.1:5000:3000"
    cpus: "0.75"
    mem_limit: 1g

  frontend:
    build: ./Web
    container_name: 4i-frontend
    restart: unless-stopped
    networks:
      - infra_internal
    ports:
      - "127.0.0.1:3000:80"
    cpus: "0.10"
    mem_limit: 128m
